###
http://localhost:3000/api/v1/products

###
GET http://localhost:3000/api/v1/products/1

###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "title": "New Product",
  "description": "This is a new product",
  "price": 100,
  "category": "electronics",
  "stock": 50
}

###
PATCH http://localhost:3000/api/v1/products/1
Content-Type: application/json

{
  "price": 150
}

###
DELETE http://localhost:3000/api/v1/products/1