###
http://localhost:3000/api/v1/products

###
GET http://localhost:3000/api/v1/products/search/the?limit=10&sort=price&order=asc

###
GET http://localhost:3000/api/v1/products/51

###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "title": "New Product",
  "description": "This is a new product",
  "price": 100,
  "category": "electronics",
  "stock": 50,
  "thumbnail": "https://m.media-amazon.com/images/M/MV5BZTdmYjExZGMtMTMzNi00OGYxLTgwOTAtMjhkMDM1ZTk4YzcyXkEyXkFqcGdeQXVyMTE5NTYwNDI2._V1_.jpg"
}

###
PATCH http://localhost:3000/api/v1/products/1
Content-Type: application/json

{
  "price": 150
}

###
DELETE http://localhost:3000/api/v1/products/1

###
POST http://localhost:3000/api/v1/products/seed

###
GET http://localhost:3000/api/v1/users

###
GET http://localhost:3000/api/v1/users/1
 
###
GET http://localhost:3000/api/v1/users/search/Gonzalez?limit=10&sort=firstName&order=asc

###
POST http://localhost:3000/api/v1/users/seed